##The website title
name: Dimitrije Markovi&#263;
##Markdown processor
markdown: kramdown
##syntax highlighter
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: /
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: Scientific homepage of Dimitrije Markovic
##Some frequently used keywords on your website
keywords: neuroscience, variation inference, probabilistic inference, decision making, human learning 

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  email: dimitrije.markovic@tu-dresden.de
  github: dimarkov

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: thumbnail.jpg
##comment this if you want full width posts with no sidebar
sidebar: on
